version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - echo "Installing dependencies"
      - pip install --no-cache-dir -r requirements.txt
  build:
    commands:
      - echo "Running tests"
      - pytest -s -v
artifacts:
  files:
    - "**/*"